# TP1 : Build the first Deep Learning NN with Keras

Our main goal is to predict the churn rate of a certain bank, that is, the customer who will leave this banking service. The predected variable (exited) is categorical, so we are dealing with a classification problem.

# 1- Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


# 2- Preprocessing data

In [2]:
# Importing the dataset using pandas
dataset = pd.read_csv('data.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

## 2.1- Exploring data

In [3]:
dataset.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [4]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [ ]:
dataset.Gender.value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

## 2.2- Dividing data to features and targets

In [ ]:
# Create matrix of features and matrix of target variable.
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [ ]:
X[:,1:3]

array([['France', 'Female'],
       ['Spain', 'Female'],
       ['France', 'Female'],
       ...,
       ['France', 'Female'],
       ['Germany', 'Male'],
       ['France', 'Female']], dtype=object)

In [ ]:
X[100]

array([665, 'France', 'Female', 40, 6, 0.0, 1, 1, 1, 161848.03],
      dtype=object)

## 2.3- Encoding data

In [ ]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [ ]:
X[100]

array([665, 0, 0, 40, 6, 0.0, 1, 1, 1, 161848.03], dtype=object)

In [ ]:
X[:,1:3]

array([[0, 0],
       [2, 0],
       [0, 0],
       ...,
       [0, 0],
       [1, 1],
       [0, 0]], dtype=object)

In [ ]:
print(labelencoder_X_1.classes_)
print(labelencoder_X_2.classes_)

['France' 'Germany' 'Spain']
['Female' 'Male']


In [ ]:
print(labelencoder_X_1.inverse_transform([0,1,2,2,1,0]))
print(labelencoder_X_2.inverse_transform([0,1,1,0]))

['France' 'Germany' 'Spain' 'Spain' 'Germany' 'France']
['Female' 'Male' 'Male' 'Female']


## 2.4- One hot encoding data

In [ ]:
# one hot encoding the Geography dimension at the index 1 categorical_features = [1]
onehotencoder = OneHotEncoder(categorical_features = [1])
# it replace the second column (index=1) and replace it with 3 columns at the biggining of the matrix X
X = onehotencoder.fit_transform(X).toarray()
# We remove the first dimension X[:,0] because we just need 2 bits (dimensions, columns) instead of 3 bits 
X = X[:, 1:]

/media/DATA/miniconda/envs/edx/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/media/DATA/miniconda/envs/edx/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [ ]:
# There is 10 features
print(X.shape)

(10000, 11)


In [ ]:
X[1]

array([0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
       4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.1254258e+05])

## 2.5- Dividing data to training and test sets 

In [ ]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## 2.6- Scaling data

In [ ]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 3- Creating NN and training it

## 3.1- Building the Neuraul Network

In [ ]:
#Initializing Neural Network
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


/media/DATA/miniconda/envs/edx/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/media/DATA/miniconda/envs/edx/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
/media/DATA/miniconda/envs/edx/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


## 3.2- Define all functions for compilation

1- optimizer : the optimization technique for Gradient descent

2- loss : the cost (loss) function

3- metrics : define what metrics are used for evaluation during training

In [ ]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 14s 2ms/step - loss: 0.4871 - acc: 0.7975
Epoch 2/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4256 - acc: 0.7982
Epoch 3/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4194 - acc: 0.7996
Epoch 4/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4153 - acc: 0.8214
Epoch 5/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4130 - acc: 0.8304
Epoch 6/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4107 - acc: 0.8336
Epoch 7/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4095 - acc: 0.8336
Epoch 8/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4076 - acc: 0.8344
Epoch 9/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4063 - acc: 0.8357
Epoch 10/100
8000/8000 [=============================

## 3.3- Predicting the Test set results

In [ ]:
# We feed the test data into the model
y_pred = classifier.predict(X_test)
# We get probability values (between 0 and 1)
# For a 0.5 threshold we decide if the client will exit the Bank
y_pred = (y_pred > 0.5)
print(y_pred)

## 3.4- Creating the Confusion Matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
# Calculating the Accuracy of our model
accuracy = (cm[0,0]+cm[1,1]) * 100/ cm.sum()
print("The accuracy of our model is %2.1f %%" % accuracy)